Added a debugger for github OIDC login issue

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -35,13 +35,60 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v6
 
+
+###################Inscpect GitHub OIDC claims########################
+
+      # - name: Inspect GitHub OIDC claims
+      #   env:
+      #     ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #     ACTIONS_ID_TOKEN_REQUEST_URL: ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}
+      #   run: |
+      #     RESPONSE=$(curl -sSf \
+      #       -H "Authorization: bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" \
+      #       -H "Accept: application/json; api-version=2.0" \
+      #       "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com")
+
+      #     TOKEN=$(echo "$RESPONSE" | jq -r '.value')
+
+      #     if [ -z "$TOKEN" ] || [ "$TOKEN" = "null" ]; then
+      #       echo "Failed to obtain OIDC token"
+      #       exit 1
+      #     fi
+
+      #     PAYLOAD=$(echo "$TOKEN" | cut -d '.' -f 2)
+
+      #     case $((${#PAYLOAD} % 4)) in
+      #       2) PAYLOAD="${PAYLOAD}==" ;;
+      #       3) PAYLOAD="${PAYLOAD}=" ;;
+      #     esac
+
+      #     echo "$PAYLOAD" | base64 -d 2>/dev/null | jq '{
+      #       iss,
+      #       aud,
+      #       sub,
+      #       repository,
+      #       repository_owner,
+      #       repository_id,
+      #       repository_owner_id,
+      #       ref,
+      #       ref_type,
+      #       event_name
+      #     }'
+
       - name: Inspect GitHub OIDC claims
-        env:
-          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          ACTIONS_ID_TOKEN_REQUEST_URL: ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}
         run: |
+          echo "========== GITHUB CONTEXT =========="
+          echo "Repository: $GITHUB_REPOSITORY"
+          echo "Ref:        $GITHUB_REF"
+          echo "Branch:     $GITHUB_REF_NAME"
+          echo "Event:      $GITHUB_EVENT_NAME"
+          echo "SHA:        $GITHUB_SHA"
+
+          echo ""
+          echo "========== OIDC TOKEN =========="
+
           RESPONSE=$(curl -sSf \
-            -H "Authorization: bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" \
+            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
             -H "Accept: application/json; api-version=2.0" \
             "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com")
 
@@ -71,6 +118,9 @@ jobs:
             ref_type,
             event_name
           }'
+
+  ##############################################################3
+
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v6
         with:
